### ISSUE TITLE
Support for 4.02 missing from the opam-repository

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [diml/ppxfind#4]
So, I can't fathom why, but the opam repository seems to disagree with the `.opam` file in this repo. Despite #2, the version on opam now demands OCaml >=4.03:

```
ppx_deriving npm-build* $ opam info ppxfind       

<><> ppxfind: information on all versions <><><><><><><><><><><><><><><><><>  🐫 
name                   ppxfind
all-installed-versions 1.2 [default /Users/ec/Sync/Documents/Miscellany/RWO]
all-versions           1.1  1.2

<><> Version-specific details <><><><><><><><><><><><><><><><><><><><><><><>  🐫 
version       1.2
repository    default
url.src:      "https://github.com/diml/ppxfind/releases/download/1.2/ppxfind-1.2.tbz"
... snip ...
depends:      "ocaml" {>= "4.03.0"}
              "jbuilder" {build & >= "1.0+beta16"}
              "ocaml-migrate-parsetree"
              "ocamlfind"
conflicts:    "dune" {= "1.2.0" | = "1.2.1"}
synopsis      ocamlfind ppx tool
description   Ppxfind is a small command line tool that among other things allows
              to use old style ppx rewriters with jbuilder.
```

(This seems to have been caused by ocaml/opam-repository@7cb952d1492ae0224dad1da51ee8495d0e3a7bb7.)

Any chance we could get this repaired? It's causing me some problems in building existing OCaml packages for BuckleScript. `]=`

**Comment by diml** [comment]
Fixing this seems good. Could you try building ppxfind ocaml 4.02 to see if its just the opam file that's wrong or if it is a real build failure? I'd try it myself but I don't have a 4.02 compiler installed and it takes long to build...

**Comment by ELLIOTTCABLE** [comment]
My Issue, my work! Happy to give it a try, as long as the build process is pretty straightforward. Trying now.

K, works on 4.02.3, although I needed to fix two warnings (#5). I'm not sure what @kit-ty-kate had trouble with, but looks fine on 4.02 over here! `¯\_(ツ)_/¯`

**Comment by diml** [comment]
Alright, thanks for looking into this :) I just noticed that ppxfind is still using jbuilder, so I'll prepare a new release using dune and `ocaml >= 4.02` and we can see how it goes.

**Comment by diml** [comment]
Done: https://github.com/ocaml/opam-repository/pull/14132
